# LLM settings
BASE_LLM_MODEL_NAME = 'gpt-4o'
TEMPERATURE = 0.3

#SQL DB Tool settings
SQL_DB_TOOL_PRODUCT_DB_URI = "sqlite:///Data/database.db"
SQL_DB_TOOL_LLM_MODEL_NAME = "gpt-4o"
SQL_DB_TOOL_LLM_MODEL_TEMPERATURE = 0.5
SQL_DB_TOOL_TOP_K = 10
SQL_DB_TOOL_MAX_ATTEMPTS = 3